### ISSUE TITLE
News site

### ISSUE THREAD

**Issue by Hornebom** [centrifuge/website#591]

**Comment by annamehr** [comment]
@Hornebom where can I find the news site?

**Comment by annamehr** [comment]
@Hornebom I realized few things are missing from the design
* showing outlet instead of date
* underline `read more`
* preview text is missing 
![Screenshot 2023-02-08 at 15.57.10.png](https://images.zenhubusercontent.com/5af53feb4b5806bc2bd2bad8/cc5e6405-8fe5-4c80-8d6c-636d731145bd)
![Screenshot 2023-02-08 at 15.24.48.png](https://images.zenhubusercontent.com/5af53feb4b5806bc2bd2bad8/4c6546a5-00ea-446a-bef6-961c89811599)

**Comment by Hornebom** [comment]
@annamehr 
> showing outlet instead of date
Outlet is an array. Should I display all of them or just the first one?

> preview text is missing
The editors can fill in a description for the post. I could use this description to render the preview. Currently none of the posts has such a description

**Comment by Hornebom** [comment]
Solved within https://github.com/centrifuge/website/pull/671
